#include "stdafx.h"

#define ARTICULATE_SUBJECT_ALL 0x80000000
#define ARTICULATE_SUBJECT_TEAM_RED 0x01000000
#define ARTICULATE_SUBJECT_TEAM_BLUE 0x02000000
#define ARTICULATE_SUBJECT_TEAM_GREEN 0x04000000
#define ARTICULATE_SUBJECT_TEAM_YELLOW 0x08000000
#define ARTICULATE_SUBJECT_TEAM_WHITE 0x10000000

#define ARTICULATE_UNIT_2 0x2
#define ARTICULATE_UNIT_3 0x4
#define ARTICULATE_UNIT_4 0x8
#define ARTICULATE_UNIT_5 0x10
#define ARTICULATE_UNIT_6 0x20
#define ARTICULATE_UNIT_7 0x40
#define ARTICULATE_UNIT_8 0x80
#define ARTICULATE_UNIT_9 0x100
#define ARTICULATE_UNIT_10 0x200
#define ARTICULATE_UNIT_11 0x400
#define ARTICULATE_UNIT_12 0x800
#define ARTICULATE_UNIT_13 0x1000
#define ARTICULATE_UNIT_14 0x2000
#define ARTICULATE_UNIT_15 0x4000
#define ARTICULATE_UNIT_16 0x8000
#define ARTICULATE_UNIT_17 0x10000
#define ARTICULATE_UNIT_18 0x20000
#define ARTICULATE_UNIT_19 0x40000
#define ARTICULATE_UNIT_20 0x80000
#define ARTICULATE_UNIT_21 0x100000
#define ARTICULATE_UNIT_22 0x200000
#define ARTICULATE_UNIT_23 0x400000
#define ARTICULATE_UNIT_24 0x800000

/**
	Articulate Commands
*/

#define ARTICULATE_COMMAND_MOVE 0x0100
#define ARTICULATE_COMMAND_MOVE_RETURN ARTICULATE_COMMAND_MOVE | 0x1
#define ARTICULATE_COMMAND_MOVE_ADVANCE ARTICULATE_COMMAND_MOVE | 0x2
#define ARTICULATE_COMMAND_MOVE_STAYBACK ARTICULATE_COMMAND_MOVE | 0x3
#define ARTICULATE_COMMAND_MOVE_FLANKLEFT ARTICULATE_COMMAND_MOVE | 0x4
#define ARTICULATE_COMMAND_MOVE_FLANKRIGHT ARTICULATE_COMMAND_MOVE | 0x5
#define ARTICULATE_COMMAND_MOVE_STOP ARTICULATE_COMMAND_MOVE | 0x6
#define ARTICULATE_COMMAND_MOVE_WAITFORME ARTICULATE_COMMAND_MOVE | 0x7
#define ARTICULATE_COMMAND_MOVE_COVER ARTICULATE_COMMAND_MOVE | 0x8
#define ARTICULATE_COMMAND_MOVE_NEXTWAYPOINT ARTICULATE_COMMAND_MOVE | 0x9

#define ARTICULATE_COMMAND_MOVE_CURSOR ARTICULATE_COMMAND_MOVE | 0xA



#define ARTICULATE_COMMAND_TARGET 0x0200
#define ARTICULATE_COMMAND_TARGET_MENU ARTICULATE_COMMAND_TARGET | 0x1
#define ARTICULATE_COMMAND_TARGET_CANCEL ARTICULATE_COMMAND_TARGET | 0x2

#define ARTICULATE_COMMAND_TARGET_CURSOR ARTICULATE_COMMAND_TARGET | 0xA



#define ARTICULATE_COMMAND_ENGAGE 0x0300
#define ARTICULATE_COMMAND_ENGAGE_OPENFIRE ARTICULATE_COMMAND_ENGAGE | 0x1
#define ARTICULATE_COMMAND_ENGAGE_HOLDFIRE ARTICULATE_COMMAND_ENGAGE | 0x2
#define ARTICULATE_COMMAND_ENGAGE_FIRE ARTICULATE_COMMAND_ENGAGE | 0x3
#define ARTICULATE_COMMAND_ENGAGE_ENGAGE ARTICULATE_COMMAND_ENGAGE | 0x4
#define ARTICULATE_COMMAND_ENGAGE_ENGAGEATWILL ARTICULATE_COMMAND_ENGAGE | 0x5
#define ARTICULATE_COMMAND_ENGAGE_DISENGAGE ARTICULATE_COMMAND_ENGAGE | 0x6
#define ARTICULATE_COMMAND_ENGAGE_SCANHORIZON ARTICULATE_COMMAND_ENGAGE | 0x7

#define ARTICULATE_COMMAND_ENGAGE_WATCH ARTICULATE_COMMAND_ENGAGE | 0x10
#define ARTICULATE_COMMAND_ENGAGE_WATCH_NORTH ARTICULATE_COMMAND_ENGAGE_WATCH | 0x1
#define ARTICULATE_COMMAND_ENGAGE_WATCH_NORTHEAST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x2
#define ARTICULATE_COMMAND_ENGAGE_WATCH_EAST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x3
#define ARTICULATE_COMMAND_ENGAGE_WATCH_SOUTHEAST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x4
#define ARTICULATE_COMMAND_ENGAGE_WATCH_SOUTH ARTICULATE_COMMAND_ENGAGE_WATCH | 0x5
#define ARTICULATE_COMMAND_ENGAGE_WATCH_SOUTHWEST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x6
#define ARTICULATE_COMMAND_ENGAGE_WATCH_WEST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x7
#define ARTICULATE_COMMAND_ENGAGE_WATCH_NORTHWEST ARTICULATE_COMMAND_ENGAGE_WATCH | 0x8

#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS ARTICULATE_COMMAND_ENGAGE | 0x20
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_NORTH ARTICULATE_COMMAND_ENGAGE | 0x1
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_NORTHEAST ARTICULATE_COMMAND_ENGAGE | 0x2
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_EAST ARTICULATE_COMMAND_ENGAGE | 0x3
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_SOUTHEAST ARTICULATE_COMMAND_ENGAGE | 0x4
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_SOUTH ARTICULATE_COMMAND_ENGAGE | 0x5
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_SOUTHWEST ARTICULATE_COMMAND_ENGAGE | 0x6
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_WEST ARTICULATE_COMMAND_ENGAGE | 0x7
#define ARTICULATE_COMMAND_ENGAGE_SUPPRESS_NORTHWEST ARTICULATE_COMMAND_ENGAGE | 0x8

struct ArticulateCommand {
	int Subjects;
	int Command;
};

void GenerateScript(ArticulateCommand* command, char* output, int outputSize);